M48
; DRILL file {KiCad 7.0.7} date Mon Dec 18 21:45:09 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-12-18T21:45:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X61.503Y-43.407
X61.503Y-99.147
X163.543Y-43.407
X163.543Y-99.147
T0
M30
